# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/cpre480/SGP/hw/constrs/NexysVideo_Master.xdc

# TCL: U:/cpre480/SGP/hw/constrs/axis_async_fifo.tcl

# TCL: U:/cpre480/SGP/hw/constrs/eth_mac_1g_rgmii.tcl

# TCL: U:/cpre480/SGP/hw/constrs/eth_mac_fifo.tcl

# TCL: U:/cpre480/SGP/hw/constrs/rgmii_phy_if.tcl

# TCL: U:/cpre480/SGP/hw/constrs/sync_reset.tcl

# XDC: U:/cpre480/SGP/hw/constrs/vdma_timing_workaround.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_0_0 || ORIG_REF_NAME==design_1_mdm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntrl_0_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntrl_0_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mm2s_mapper_0_0/design_1_axi_mm2s_mapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mm2s_mapper_0_0 || ORIG_REF_NAME==design_1_axi_mm2s_mapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_rx_udp_0/design_1_axis_data_fifo_rx_udp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_rx_udp_0 || ORIG_REF_NAME==design_1_axis_data_fifo_rx_udp_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_tx_udp_0/design_1_axis_data_fifo_tx_udp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_tx_udp_0 || ORIG_REF_NAME==design_1_axis_data_fifo_tx_udp_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_rx_tagger_0_0/design_1_axis_rx_tagger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_rx_tagger_0_0 || ORIG_REF_NAME==design_1_axis_rx_tagger_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_tx_tagger_0_0/design_1_axis_tx_tagger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_tx_tagger_0_0 || ORIG_REF_NAME==design_1_axis_tx_tagger_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_udp_ethernet_0_0/design_1_axis_udp_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_udp_ethernet_0_0 || ORIG_REF_NAME==design_1_axis_udp_ethernet_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_renderOutput_0/design_1_sgp_renderOutput_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_renderOutput_0 || ORIG_REF_NAME==design_1_sgp_renderOutput_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_000_fifo_0/design_1_attrib_000_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_000_fifo_0 || ORIG_REF_NAME==design_1_attrib_000_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_001_fifo_0/design_1_attrib_001_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_001_fifo_0 || ORIG_REF_NAME==design_1_attrib_001_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_010_fifo_0/design_1_attrib_010_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_010_fifo_0 || ORIG_REF_NAME==design_1_attrib_010_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_011_fifo_0/design_1_attrib_011_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_011_fifo_0 || ORIG_REF_NAME==design_1_attrib_011_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertexFetch_core_0_0/design_1_vertexFetch_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertexFetch_core_0_0 || ORIG_REF_NAME==design_1_vertexFetch_core_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertex_attrib_switch_0/design_1_vertex_attrib_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertex_attrib_switch_0 || ORIG_REF_NAME==design_1_vertex_attrib_switch_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertex_buffer_FIFO_0/design_1_vertex_buffer_FIFO_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertex_buffer_FIFO_0 || ORIG_REF_NAME==design_1_vertex_buffer_FIFO_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_viewPort_0/design_1_sgp_viewPort_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_viewPort_0 || ORIG_REF_NAME==design_1_sgp_viewPort_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertexfetch_fifo_0/design_1_vertexfetch_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertexfetch_fifo_0 || ORIG_REF_NAME==design_1_vertexfetch_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_viewport_fifo_0/design_1_viewport_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_viewport_fifo_0 || ORIG_REF_NAME==design_1_viewport_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_interface_0 || ORIG_REF_NAME==design_1_mem_interface_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_memory_dma_0/design_1_memory_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_memory_dma_0 || ORIG_REF_NAME==design_1_memory_dma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_memory_intercon_0/design_1_memory_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_memory_intercon_0 || ORIG_REF_NAME==design_1_memory_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_periph_intercon_0/design_1_periph_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_periph_intercon_0 || ORIG_REF_NAME==design_1_periph_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_dma_0/design_1_system_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_dma_0 || ORIG_REF_NAME==design_1_system_dma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dynclk_0_0/design_1_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dynclk_0_0 || ORIG_REF_NAME==design_1_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0_0/design_1_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_rasterizer_0_0/design_1_sgp_rasterizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_rasterizer_0_0 || ORIG_REF_NAME==design_1_sgp_rasterizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_11/design_1_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_11 || ORIG_REF_NAME==design_1_auto_pc_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_8 || ORIG_REF_NAME==design_1_auto_pc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_9/design_1_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_9 || ORIG_REF_NAME==design_1_auto_pc_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_10/design_1_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_10 || ORIG_REF_NAME==design_1_auto_pc_10} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
