# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/cpre480/SGP/hw/constrs/NexysVideo_Master.xdc

# TCL: U:/cpre480/SGP/hw/constrs/axis_async_fifo.tcl

# TCL: U:/cpre480/SGP/hw/constrs/eth_mac_1g_rgmii.tcl

# TCL: U:/cpre480/SGP/hw/constrs/eth_mac_fifo.tcl

# TCL: U:/cpre480/SGP/hw/constrs/rgmii_phy_if.tcl

# TCL: U:/cpre480/SGP/hw/constrs/sync_reset.tcl

# XDC: U:/cpre480/SGP/hw/constrs/vdma_timing_workaround.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_0_0 || ORIG_REF_NAME==design_1_mdm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntrl_0_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntrl_0_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mm2s_mapper_0_0/design_1_axi_mm2s_mapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mm2s_mapper_0_0 || ORIG_REF_NAME==design_1_axi_mm2s_mapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_rx_udp_0/design_1_axis_data_fifo_rx_udp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_rx_udp_0 || ORIG_REF_NAME==design_1_axis_data_fifo_rx_udp_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_tx_udp_0/design_1_axis_data_fifo_tx_udp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_tx_udp_0 || ORIG_REF_NAME==design_1_axis_data_fifo_tx_udp_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_rx_tagger_0_0/design_1_axis_rx_tagger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_rx_tagger_0_0 || ORIG_REF_NAME==design_1_axis_rx_tagger_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_tx_tagger_0_0/design_1_axis_tx_tagger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_tx_tagger_0_0 || ORIG_REF_NAME==design_1_axis_tx_tagger_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_udp_ethernet_0_0/design_1_axis_udp_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_udp_ethernet_0_0 || ORIG_REF_NAME==design_1_axis_udp_ethernet_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_renderOutput_0/design_1_sgp_renderOutput_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_renderOutput_0 || ORIG_REF_NAME==design_1_sgp_renderOutput_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_000_fifo_0/design_1_attrib_000_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_000_fifo_0 || ORIG_REF_NAME==design_1_attrib_000_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_001_fifo_0/design_1_attrib_001_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_001_fifo_0 || ORIG_REF_NAME==design_1_attrib_001_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_010_fifo_0/design_1_attrib_010_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_010_fifo_0 || ORIG_REF_NAME==design_1_attrib_010_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_attrib_011_fifo_0/design_1_attrib_011_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_attrib_011_fifo_0 || ORIG_REF_NAME==design_1_attrib_011_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertexFetch_core_0_0/design_1_vertexFetch_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertexFetch_core_0_0 || ORIG_REF_NAME==design_1_vertexFetch_core_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertex_attrib_switch_0/design_1_vertex_attrib_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertex_attrib_switch_0 || ORIG_REF_NAME==design_1_vertex_attrib_switch_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertex_buffer_FIFO_0/design_1_vertex_buffer_FIFO_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertex_buffer_FIFO_0 || ORIG_REF_NAME==design_1_vertex_buffer_FIFO_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_viewPort_0/design_1_sgp_viewPort_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_viewPort_0 || ORIG_REF_NAME==design_1_sgp_viewPort_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_g_inst_0 || ORIG_REF_NAME==bd_f60c_g_inst_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/bd_f60c_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_aw_0 || ORIG_REF_NAME==bd_f60c_slot_0_aw_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/bd_f60c_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_w_0 || ORIG_REF_NAME==bd_f60c_slot_0_w_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/bd_f60c_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_b_0 || ORIG_REF_NAME==bd_f60c_slot_0_b_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/bd_f60c_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_ar_0 || ORIG_REF_NAME==bd_f60c_slot_0_ar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/bd_f60c_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_r_0 || ORIG_REF_NAME==bd_f60c_slot_0_r_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vertexfetch_fifo_0/design_1_vertexfetch_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vertexfetch_fifo_0 || ORIG_REF_NAME==design_1_vertexfetch_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_viewport_fifo_0/design_1_viewport_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_viewport_fifo_0 || ORIG_REF_NAME==design_1_viewport_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_interface_0 || ORIG_REF_NAME==design_1_mem_interface_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_memory_dma_0/design_1_memory_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_memory_dma_0 || ORIG_REF_NAME==design_1_memory_dma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_memory_intercon_0/design_1_memory_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_memory_intercon_0 || ORIG_REF_NAME==design_1_memory_intercon_0} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_memory_intercon_0/bd_0/bd_6231.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_0/bd_6231_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_1/bd_6231_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_2/bd_6231_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_3/bd_6231_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_4/bd_6231_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_5/bd_6231_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_6/bd_6231_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_7/bd_6231_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_8/bd_6231_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_9/bd_6231_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_10/bd_6231_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_11/bd_6231_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_12/bd_6231_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_13/bd_6231_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_14/bd_6231_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_15/bd_6231_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_16/bd_6231_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_17/bd_6231_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_18/bd_6231_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_19/bd_6231_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_20/bd_6231_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_21/bd_6231_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_22/bd_6231_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_23/bd_6231_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_24/bd_6231_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_25/bd_6231_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_26/bd_6231_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_27/bd_6231_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_28/bd_6231_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_29/bd_6231_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_30/bd_6231_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_31/bd_6231_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_32/bd_6231_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_33/bd_6231_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_34/bd_6231_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_35/bd_6231_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_36/bd_6231_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_37/bd_6231_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_38/bd_6231_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_39/bd_6231_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_40/bd_6231_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_41/bd_6231_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_42/bd_6231_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_43/bd_6231_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_44/bd_6231_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_45/bd_6231_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_46/bd_6231_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_47/bd_6231_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_48/bd_6231_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_49/bd_6231_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_50/bd_6231_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_51/bd_6231_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_52/bd_6231_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_53/bd_6231_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_54/bd_6231_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_55/bd_6231_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_56/bd_6231_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_57/bd_6231_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_periph_intercon_0/design_1_periph_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_periph_intercon_0 || ORIG_REF_NAME==design_1_periph_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_dma_0/design_1_system_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_dma_0 || ORIG_REF_NAME==design_1_system_dma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dynclk_0_0/design_1_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dynclk_0_0 || ORIG_REF_NAME==design_1_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0_0/design_1_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_rasterizer_0_0/design_1_sgp_rasterizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sgp_rasterizer_0_0 || ORIG_REF_NAME==design_1_sgp_rasterizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sgp_rasterizer_0_0/src/shared_divider/shared_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_divider || ORIG_REF_NAME==shared_divider} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_11/design_1_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_11 || ORIG_REF_NAME==design_1_auto_pc_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_8 || ORIG_REF_NAME==design_1_auto_pc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_9/design_1_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_9 || ORIG_REF_NAME==design_1_auto_pc_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_10/design_1_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_10 || ORIG_REF_NAME==design_1_auto_pc_10} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_0_0 || ORIG_REF_NAME==design_1_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0_ooc_trace.xdc

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axis_udp_ethernet_0_0/src/eth.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axis_udp_ethernet_0_0 || ORIG_REF_NAME==design_1_axis_udp_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_vertex_attrib_switch_0/design_1_vertex_attrib_switch_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc

# XDC: bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0/user_design/constraints/design_1_mem_interface_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_interface_0 || ORIG_REF_NAME==design_1_mem_interface_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0/user_design/constraints/design_1_mem_interface_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_dma_0/design_1_memory_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_memory_dma_0 || ORIG_REF_NAME==design_1_memory_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_1/bd_6231_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_1/bd_6231_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_2/bd_6231_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_2/bd_6231_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_3/bd_6231_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_3/bd_6231_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_4/bd_6231_arsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_5/bd_6231_rsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_6/bd_6231_awsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_7/bd_6231_wsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_8/bd_6231_bsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_12/bd_6231_s00a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_13/bd_6231_sarn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_14/bd_6231_srn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_15/bd_6231_sawn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_16/bd_6231_swn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_17/bd_6231_sbn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_21/bd_6231_s01a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_22/bd_6231_sarn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_23/bd_6231_srn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_27/bd_6231_s02a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_28/bd_6231_sarn_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_29/bd_6231_srn_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_30/bd_6231_sawn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_31/bd_6231_swn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_32/bd_6231_sbn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_36/bd_6231_s03a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_37/bd_6231_sarn_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_38/bd_6231_srn_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_39/bd_6231_sawn_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_40/bd_6231_swn_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_41/bd_6231_sbn_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_45/bd_6231_s04a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_46/bd_6231_sarn_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_47/bd_6231_srn_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_48/bd_6231_sawn_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_49/bd_6231_swn_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_50/bd_6231_sbn_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_51/bd_6231_m00s2a_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_52/bd_6231_m00arn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_53/bd_6231_m00rn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_54/bd_6231_m00awn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_55/bd_6231_m00wn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/bd_0/ip/ip_56/bd_6231_m00bn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_memory_intercon_0/ooc.xdc

# XDC: bd/design_1/ip/design_1_system_dma_0/design_1_system_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_system_dma_0 || ORIG_REF_NAME==design_1_system_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_pc_11/design_1_auto_pc_11_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_9/design_1_auto_pc_9_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_10/design_1_auto_pc_10_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
