# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_sgp_rasterizer_0_0/design_1_sgp_rasterizer_0_0.xci
# IP: The module: 'design_1_sgp_rasterizer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_sgp_rasterizer_0_0/src/shared_divider/shared_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_divider || ORIG_REF_NAME==shared_divider} -quiet] -quiet

# IP: u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_sgp_rasterizer_0_0/design_1_sgp_rasterizer_0_0.xci
# IP: The module: 'design_1_sgp_rasterizer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_sgp_rasterizer_0_0/src/shared_divider/shared_divider.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_divider || ORIG_REF_NAME==shared_divider} -quiet] -quiet
