set_property SRC_FILE_INFO {cfile:u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0/design_1_mdm_0_0_in_context.xdc rfile:../../../sgp_system.srcs/sources_1/bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0/design_1_mdm_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/debug_subsystem/mdm_0} [current_design]
set_property SRC_FILE_INFO {cfile:u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0_in_context.xdc rfile:../../../sgp_system.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0/design_1_dlmb_bram_if_cntrl_0_0_in_context.xdc id:2 order:EARLY scoped_inst:design_1_i/debug_subsystem/microblaze_0_local_memory/dlmb_bram_if_cntrl_0} [current_design]
set_property SRC_FILE_INFO {cfile:u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0_in_context.xdc rfile:../../../sgp_system.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0/design_1_ilmb_bram_if_cntrl_0_0_in_context.xdc id:3 order:EARLY scoped_inst:design_1_i/debug_subsystem/microblaze_0_local_memory/ilmb_bram_if_cntrl_0} [current_design]
set_property SRC_FILE_INFO {cfile:u:/cpre480/SGP/hw/proj/sgp_system.srcs/sources_1/bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0/design_1_mem_interface_0_in_context.xdc rfile:../../../sgp_system.srcs/sources_1/bd/design_1/ip/design_1_mem_interface_0/design_1_mem_interface_0/design_1_mem_interface_0_in_context.xdc id:4 order:EARLY scoped_inst:design_1_i/memory_subsystem/mem_interface} [current_design]
set_property SRC_FILE_INFO {cfile:U:/cpre480/SGP/hw/constrs/NexysVideo_Master.xdc rfile:../../../../constrs/NexysVideo_Master.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:U:/cpre480/SGP/hw/constrs/vdma_timing_workaround.xdc rfile:../../../../constrs/vdma_timing_workaround.xdc id:6} [current_design]
current_instance design_1_i/debug_subsystem/mdm_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 [get_ports {}]
current_instance
current_instance design_1_i/debug_subsystem/microblaze_0_local_memory/dlmb_bram_if_cntrl_0
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance design_1_i/debug_subsystem/microblaze_0_local_memory/ilmb_bram_if_cntrl_0
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance design_1_i/memory_subsystem/mem_interface
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 6.250 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R4    IOSTANDARD LVCMOS33 } [get_ports { sys_clk_i }]; #IO_L13P_T2_MRCC_34 Sch=sysclk
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS15} [get_ports reset]
set_property src_info {type:XDC file:5 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD TMDS_33} [get_ports TMDS_OUT_clk_n]
set_property src_info {type:XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD TMDS_33} [get_ports TMDS_OUT_clk_p]
set_property src_info {type:XDC file:5 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[0]}]
set_property src_info {type:XDC file:5 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[0]}]
set_property src_info {type:XDC file:5 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[1]}]
set_property src_info {type:XDC file:5 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[1]}]
set_property src_info {type:XDC file:5 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_n[2]}]
set_property src_info {type:XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports {TMDS_OUT_data_p[2]}]
set_property src_info {type:XDC file:5 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V13 IOSTANDARD LVCMOS25} [get_ports RGMII_eth_phy_rx_clk]
set_property src_info {type:XDC file:5 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB16 IOSTANDARD LVCMOS25} [get_ports {RGMII_eth_phy_rxd[0]}]
set_property src_info {type:XDC file:5 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA15 IOSTANDARD LVCMOS25} [get_ports {RGMII_eth_phy_rxd[1]}]
set_property src_info {type:XDC file:5 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB15 IOSTANDARD LVCMOS25} [get_ports {RGMII_eth_phy_rxd[2]}]
set_property src_info {type:XDC file:5 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB11 IOSTANDARD LVCMOS25} [get_ports {RGMII_eth_phy_rxd[3]}]
set_property src_info {type:XDC file:5 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W10 IOSTANDARD LVCMOS25} [get_ports RGMII_eth_phy_rx_ctl]
set_property src_info {type:XDC file:5 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA14 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports RGMII_eth_phy_tx_clk]
set_property src_info {type:XDC file:5 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y12 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {RGMII_eth_phy_txd[0]}]
set_property src_info {type:XDC file:5 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W12 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {RGMII_eth_phy_txd[1]}]
set_property src_info {type:XDC file:5 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W11 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {RGMII_eth_phy_txd[2]}]
set_property src_info {type:XDC file:5 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y11 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {RGMII_eth_phy_txd[3]}]
set_property src_info {type:XDC file:5 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V10 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports RGMII_eth_phy_tx_ctl]
set_property src_info {type:XDC file:5 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U7 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 12} [get_ports RGMII_eth_phy_reset_n]
set_property src_info {type:XDC file:5 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y14 IOSTANDARD LVCMOS25} [get_ports RGMII_eth_phy_int_n]
set_property src_info {type:XDC file:5 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W14 IOSTANDARD LVCMOS25} [get_ports RGMII_eth_phy_pme_n]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical  -filter "NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*rst_reg[*]"]
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical  -filter "NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*rst_reg_reg"]
set_property src_info {type:XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_pins  -hierarchical  -filter "NAME =~*axi_vdma_0*MM2S*LB_BUILT_IN*/*rstbt*/*PRE"]
